security:
    # Configuration du hachage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    # Configuration des fournisseurs d'utilisateurs
    providers:
        # Supprimez le fournisseur users_in_memory car nous n'en avons plus besoin
        # users_in_memory: { memory: null }
        
        # Utilisation du fournisseur d'utilisateurs basé sur l'entité
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            # Utilisation du fournisseur d'utilisateurs app_user_provider
            provider: app_user_provider
           

            # Configuration de l'authentification par formulaire
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    # Configuration du contrôle d'accès
    access_control:
        # Décommentez et ajustez ces lignes selon vos besoins
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Valeur minimale pour bcrypt
                time_cost: 3 # Valeur minimale pour argon
                memory_cost: 10 # Valeur minimale pour argon